### ISSUE TITLE
kugou version error

### ISSUE THREAD

**Issue by diklios5768** [scoopcn/scoopcn#14]
![image](https://user-images.githubusercontent.com/47837462/142528885-d3e858e1-056b-4d6d-b875-56b7cf93d483.png)

Kugou change it version many times, it must have bug.

**Comment by sinloss** [comment]
I'll see to this. Thanks for your report.

**Comment by sinloss** [comment]
After several tests and experiments, I still could not find a valid place to get the latest version of it. The page content of https://download.kugou.com/ will always change from time to time. So I'll make this app `nightly` so the version inconsistency won't bother

**Comment by sinloss** [comment]
@diklios5768 Feel free to reopen this issue if you have further information and considerations to provide
