### ISSUE TITLE
dingtalk: 国内外版本不一致

### ISSUE THREAD

**Issue by wasphin** [scoopcn/scoopcn#16]
这个项目是给国内人用的还是国外人用的呢？因为我看钉钉使用的是英文版的（从检查更新的地址看），版本和国内版本是不一致的。

**Comment by sinloss** [comment]
是给国人用的。用`en-download`是因为钉钉官网上，用中文环境去下载，只能下载到一个`5Mb`大小的`dingtalk_downloader.exe`，只是一个下载器。当前方案是我**目前**所能想到的唯一一个可以下载到完整离线安装的文件方案。

我自己就在用这个版本的钉钉，只要操作系统是中文的，它安装运行之后也是中文的，用起来没什么不一样的地方。有可能跟最新版本有些不同，但是因为我没有比较过，并不很清楚。

如果您能提供一些帮助，可以让`dingtalk`完美地下载到最新版本，那就是最好不过了。

**Comment by wasphin** [comment]
下载地址格式倒是一致的，暂时也没确定的办法能查询到最新的版本信息，后面有发现我也再补充。

当前使用下载器下载到的版本是：
* 6.3.15.12108702
* hash: 4fba63672c61e024dd23a3c931b9b1f5837dd67156a5d9ffff266289ce8bb90f

开始是找一个功能发现没有，以为是版本的问题，下载最新的版本后还是没有……

**Comment by sinloss** [comment]
感谢您的反馈！
