### ISSUE TITLE
wps 中文版 不能自动关联文件格式 而且应用内的文件关联功能无法打开

### ISSUE THREAD

**Issue by zhkag** [scoopcn/scoopcn#44]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by sinloss** [comment]
> 不能自动关联文件格式  

这是因为是通过脚本将文件分步解压的，安装程序中关联文件的逻辑不会被执行。

> 应用内的文件关联功能无法打开

经过测试，在`全局设置` - `设置` - `组件管理` - `文件格式关联`中可以正常设置文件关联。

*我先关闭该 Issue 了，你可以随时再打开它。也欢迎你提出你的异议，或者提供更进一步的信息。*
